In [1]:
%run generic_pipeline.ipynb

In [35]:

import numpy as np
import pandas as pd

from FCLayer import FcLayer
from ACLayer import AcLayer
from Network import Network
from GridSearch import GridSearcher
from activation_functions import sigmoid, sigmoid_derivative, tanh, tanh_derivative, relu, relu_derivative
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report

In [3]:
learning_rate = 0.1
epochs = 1000
network1 = Network(learning_rate=learning_rate, epochs=epochs)

In [4]:
X_train.to_numpy()

array([[1.33916615e-04, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.26792251e-01, 1.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.46388715e-05, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [2.89259888e-02, 1.58730159e-02, 0.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.52664941e-02, 1.98412698e-03, 0.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [5]:
y_train.to_numpy()

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [6]:


# input_values = len(X_train.columns)
# output_values = 1
# intermediate_values = 3
# layers = 3

# for j in range(layers):
#     i = intermediate_values
#     o = intermediate_values

#     if not j:
#         i = input_values
#     elif j + 1 == layers:
#         o = output_values

#     fc = FcLayer(i, o)
#     ac = AcLayer(tanh, tanh_prime)
#     network1.add(fc)
#     network1.add(ac)

#

In [7]:
#network1.train(np.expand_dims(X_train.to_numpy(), axis=1), np.expand_dims(y_train.to_numpy(), axis=1), epochs=epochs)
network1.fit(X_train, y_train)
y_train


0  1  2  3  4  5  6  7
102  0  1  0  0  0  0  0  0
37   0  0  0  0  1  0  0  0
113  0  0  0  0  0  0  1  0
120  0  0  0  1  0  0  0  0
143  0  0  1  0  0  0  0  0
..  .. .. .. .. .. .. .. ..
108  0  1  0  0  0  0  0  0
167  0  0  0  0  0  1  0  0
0    0  0  0  0  0  1  0  0
40   0  0  1  0  0  0  0  0
145  0  1  0  0  0  0  0  0

[155 rows x 8 columns]

In [8]:
np.expand_dims(X_train.to_numpy(), axis=1).shape[2]


65

In [9]:

out = network1.predict(X_train)
out


[[0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 

In [10]:
y_train

0  1  2  3  4  5  6  7
102  0  1  0  0  0  0  0  0
37   0  0  0  0  1  0  0  0
113  0  0  0  0  0  0  1  0
120  0  0  0  1  0  0  0  0
143  0  0  1  0  0  0  0  0
..  .. .. .. .. .. .. .. ..
108  0  1  0  0  0  0  0  0
167  0  0  0  0  0  1  0  0
0    0  0  0  0  0  1  0  0
40   0  0  1  0  0  0  0  0
145  0  1  0  0  0  0  0  0

[155 rows x 8 columns]

In [11]:
X_test.shape

(39, 65)

In [12]:
parameters = {
    'learning_rate': [0.1, 0.5],
    'epochs': [1000,2000],
    'node_counts': [[3,3],[10,10],[100,100],[3,3,3],[10,10,10],[20,20,20]],
    'activation_function': [(sigmoid,sigmoid_derivative),(relu,relu_derivative),(tanh,tanh_derivative)],

}
gs = GridSearcher(network1, parameters, X_train, y_train)
gs_results = gs.search()
gs_results

1 / 72: 0.0576915593712906
2 / 72: 0.037967692967692965
3 / 72: 0.04638456848983165
4 / 72: 0.0576915593712906
5 / 72: 0.0077178030303030306
6 / 72: 0.0077178030303030306
7 / 72: 0.0077178030303030306
8 / 72: 0.0077178030303030306
9 / 72: 0.0077178030303030306
10 / 72: 0.0576915593712906
11 / 72: 0.03317155067155067
12 / 72: 0.04638456848983165
13 / 72: 0.0576915593712906
14 / 72: 0.0077178030303030306
15 / 72: 0.016220238095238097
16 / 72: 0.026024384112619404
17 / 72: 0.0077178030303030306
18 / 72: 0.01879827688651218
19 / 72: 0.0576915593712906
20 / 72: 0.040233774839038
21 / 72: 0.0670439091491723
22 / 72: 0.0576915593712906
23 / 72: 0.0077178030303030306
24 / 72: 0.014386512180629826
25 / 72: 0.0077178030303030306
26 / 72: 0.0077178030303030306
27 / 72: 0.0077178030303030306
28 / 72: 0.0576915593712906
29 / 72: 0.04266258067454876
30 / 72: 0.04638456848983165
31 / 72: 0.0576915593712906
32 / 72: 0.0077178030303030306
33 / 72: 0.03142208485958485
34 / 72: 0.020747773790536946
35 / 

params   
0   {'learning_rate': 0.1, 'epochs': 1000, 'node_c...  \
1   {'learning_rate': 0.1, 'epochs': 1000, 'node_c...   
2   {'learning_rate': 0.1, 'epochs': 1000, 'node_c...   
3   {'learning_rate': 0.1, 'epochs': 1000, 'node_c...   
4   {'learning_rate': 0.1, 'epochs': 1000, 'node_c...   
..                                                ...   
67  {'learning_rate': 0.5, 'epochs': 2000, 'node_c...   
68  {'learning_rate': 0.5, 'epochs': 2000, 'node_c...   
69  {'learning_rate': 0.5, 'epochs': 2000, 'node_c...   
70  {'learning_rate': 0.5, 'epochs': 2000, 'node_c...   
71  {'learning_rate': 0.5, 'epochs': 2000, 'node_c...   

                                           test_score   
0   [0.06547619047619048, 0.046052631578947366, 0....  \
1   [0.03472222222222222, 0.03472222222222222, 0.0...   
2   [0.06547619047619048, 0.046052631578947366, 0....   
3   [0.06547619047619048, 0.046052631578947366, 0....   
4   [0.0, 0.0078125, 0.015151515151515152, 0.00781...   
..                                                ...   
67  [0.0, 0.0078125, 0.015151515151515152, 0.00781...   
68  [0.03472222222222222, 0.03472222222222222, 0.0...   
69  [0.03472222222222222, 0.03472222222222222, 0.0...   
70  [0.0, 0.0078125, 0.015151515151515152, 0.00781...   
71  [0.028571428571428574, 0.046052631578947366, 0...   

                                             fit_time   
0   [8.432593584060669, 8.294090270996094, 8.32311...  \
1   [6.82401442527771, 6.7685463428497314, 6.80252...   
2   [5.839398384094238, 5.901453495025635, 5.82243...   
3   [8.476042747497559, 8.456154823303223, 8.53028...   
4   [7.537651538848877, 7.088119029998779, 7.32416...   
..                                                ...   
67  [22.491724252700806, 22.554781913757324, 22.71...   
68  [19.37912631034851, 19.459699392318726, 19.445...   
69  [27.706740856170654, 27.50494933128357, 27.829...   
70  [23.927967309951782, 24.109249591827393, 23.80...   
71  [21.284603357315063, 21.382659673690796, 21.63...   

                                           score_time  score_mean  
0   [0.004781961441040039, 0.005013942718505859, 0...    0.057692  
1   [0.005001068115234375, 0.004985332489013672, 0...    0.037968  
2   [0.00500178337097168, 0.004001140594482422, 0....    0.046385  
3   [0.00510406494140625, 0.0030159950256347656, 0...    0.057692  
4   [0.002997875213623047, 0.004002571105957031, 0...    0.007718  
..                                                ...         ...  
67  [0.004137992858886719, 0.005690097808837891, 0...    0.007718  
68  [0.003675699234008789, 0.0036573410034179688, ...    0.037968  
69  [0.004156351089477539, 0.0036385059356689453, ...    0.019603  
70  [0.005060911178588867, 0.003632783889770508, 0...    0.007718  
71  [0.0052242279052734375, 0.0036187171936035156,...    0.033289  

[72 rows x 5 columns]

In [13]:
gs_results["test_score"].iloc[0]

array([0.06547619, 0.04605263, 0.08510638, 0.05128205, 0.04054054])

In [14]:
gs_results["score_mean"].unique()

array([0.05769156, 0.03796769, 0.04638457, 0.0077178 , 0.03317155,
       0.01622024, 0.02602438, 0.01879828, 0.04023377, 0.06704391,
       0.01438651, 0.04266258, 0.03142208, 0.02074777, 0.02317512,
       0.14460987, 0.040116  , 0.03019193, 0.00744207, 0.10502213,
       0.00918561, 0.07484019, 0.30823794, 0.14193543, 0.01960317,
       0.03328933])

In [15]:
nn_sklearn = MLPClassifier()

In [16]:
parameters_sk = {
    'learning_rate_init': [0.01, 0.1,0.5,0.8],
    "learning_rate": ["constant"],
    'max_iter': [10,100,1000,2000],
    'hidden_layer_sizes': [[3,3],[5,5],[10,10],[50,50],[100,100],[3,3,3],[5,5,5],[10,10,10],[20,20,20]],
    'activation': ["logistic", "relu", "tanh"],
}

In [17]:
sk_nn = MLPClassifier()

gs_sk = GridSearcher(sk_nn, parameters_sk, X_train, y_train)

In [18]:
gs_results_sk = gs_sk.search()

1 / 432: 0.05137094681309077
2 / 432: 0.12988499121651298
3 / 432: 0.04198814576910552
4 / 432: 0.025505050505050503
5 / 432: 0.09341966742954969
6 / 432: 0.10850945115547517
7 / 432: 0.0
8 / 432: 0.04169244704570792
9 / 432: 0.05385302197802198
10 / 432: 0.0
11 / 432: 0.08295008912655971
12 / 432: 0.14532300302037146
13 / 432: 0.0
14 / 432: 0.2940652257099625
15 / 432: 0.3086485193550411
16 / 432: 0.032382409257409255
17 / 432: 0.11913388255703486
18 / 432: 0.05314692031603796
19 / 432: 0.06622207767154575
20 / 432: 0.09673466602309293
21 / 432: 0.043073007909964434
22 / 432: 0.01731863442389758
23 / 432: 0.049527196940990045
24 / 432: 0.0029411764705882353
25 / 432: 0.0
26 / 432: 0.0
27 / 432: 0.01388888888888889
28 / 432: 0.0
29 / 432: 0.08098647675853557
30 / 432: 0.06125541125541124
31 / 432: 0.0
32 / 432: 0.08268120768120768
33 / 432: 0.10125646997929608
34 / 432: 0.0
35 / 432: 0.28819245569245566
36 / 432: 0.32591158841158846
37 / 432: 0.3002141145891146
38 / 432: 0.380861360861

In [28]:
self_max = gs_results["score_mean"].idxmax()
print(gs_results.loc[self_max]["params"])
print(gs_results.loc[self_max]["score_mean"])

{'learning_rate': 0.5, 'epochs': 2000, 'node_counts': [10, 10], 'activation_function': (<function sigmoid at 0x0000022BA3580720>, <function sigmoid_derivative at 0x0000022BA35807C0>)}
0.3082379426129426


In [37]:
network1.set_params(**gs_results.loc[self_max]["params"])
network1.fit(X_train, y_train)
test_pred = network1.predict(X_test)


              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.80      0.80      0.80        10
           2       0.50      0.17      0.25         6
           3       0.00      0.00      0.00         0
           4       0.33      0.50      0.40         2
           5       0.38      0.60      0.46         5
           6       0.56      0.75      0.64        12
           7       0.00      0.00      0.00         1

   micro avg       0.56      0.56      0.56        39
   macro avg       0.32      0.35      0.32        39
weighted avg       0.52      0.56      0.52        39
 samples avg       0.56      0.56      0.56        39



c:\Users\vali\Documents\GitHub\Studium\ml\ML_SS_23\venv\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\vali\Documents\GitHub\Studium\ml\ML_SS_23\venv\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [38]:
print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.80      0.80      0.80        10
           2       0.50      0.17      0.25         6
           3       0.00      0.00      0.00         0
           4       0.33      0.50      0.40         2
           5       0.38      0.60      0.46         5
           6       0.56      0.75      0.64        12
           7       0.00      0.00      0.00         1

   micro avg       0.56      0.56      0.56        39
   macro avg       0.32      0.35      0.32        39
weighted avg       0.52      0.56      0.52        39
 samples avg       0.56      0.56      0.56        39



c:\Users\vali\Documents\GitHub\Studium\ml\ML_SS_23\venv\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\vali\Documents\GitHub\Studium\ml\ML_SS_23\venv\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [39]:
sk_max = gs_results_sk["score_mean"].idxmax()
print(gs_results_sk.loc[sk_max]["params"])
print(gs_results_sk.loc[sk_max]["score_mean"])

{'learning_rate_init': 0.1, 'learning_rate': 'constant', 'max_iter': 100, 'hidden_layer_sizes': [20, 20, 20], 'activation': 'relu'}
0.41042117604617606


In [40]:
sk_nn.set_params(**gs_results_sk.loc[sk_max]["params"])
network1.fit(X_train, y_train)
test_pred_sk = network1.predict(X_test)

In [41]:
print(classification_report(y_test, test_pred_sk))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.75      0.30      0.43        10
           2       0.12      0.17      0.14         6
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         2
           5       0.20      0.20      0.20         5
           6       0.56      0.83      0.67        12
           7       0.00      0.00      0.00         1

   micro avg       0.38      0.38      0.38        39
   macro avg       0.20      0.19      0.18        39
weighted avg       0.41      0.38      0.36        39
 samples avg       0.38      0.38      0.38        39



c:\Users\vali\Documents\GitHub\Studium\ml\ML_SS_23\venv\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\vali\Documents\GitHub\Studium\ml\ML_SS_23\venv\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
