In [22]:
%run generic_pipeline.ipynb

In [23]:

import numpy as np
import pandas as pd

from FCLayer import FcLayer
from ACLayer import AcLayer
from Network import Network
from GridSearch import GridSearcher
from activation_functions import sigmoid, sigmoid_derivative, tanh, tanh_derivative, relu, relu_derivative
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

In [24]:
learning_rate = 0.1
epochs = 1000
network1 = Network(learning_rate=learning_rate, epochs=epochs)

In [25]:
X_train.to_numpy()

array([[9.71341844e-02, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.14275511e-02, 2.18253968e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.09811624e-02, 5.95238095e-03, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [4.01749844e-04, 2.97619048e-03, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [9.46344076e-03, 9.92063492e-04, 0.00000000e+00, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [26]:
y_train.to_numpy()

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0]])

In [27]:


# input_values = len(X_train.columns)
# output_values = 1
# intermediate_values = 3
# layers = 3

# for j in range(layers):
#     i = intermediate_values
#     o = intermediate_values

#     if not j:
#         i = input_values
#     elif j + 1 == layers:
#         o = output_values

#     fc = FcLayer(i, o)
#     ac = AcLayer(tanh, tanh_prime)
#     network1.add(fc)
#     network1.add(ac)

#

In [28]:
#network1.train(np.expand_dims(X_train.to_numpy(), axis=1), np.expand_dims(y_train.to_numpy(), axis=1), epochs=epochs)
network1.fit(X_train, y_train)
y_train


0  1  2  3  4  5  6  7
69   0  0  0  0  0  0  1  0
190  0  0  0  0  1  0  0  0
73   0  0  0  0  0  1  0  0
162  0  0  0  0  0  1  0  0
186  0  1  0  0  0  0  0  0
..  .. .. .. .. .. .. .. ..
83   0  0  0  0  0  1  0  0
39   0  0  0  0  0  1  0  0
140  0  1  0  0  0  0  0  0
70   0  0  0  0  0  0  1  0
131  0  0  0  0  0  1  0  0

[155 rows x 8 columns]

In [29]:
np.expand_dims(X_train.to_numpy(), axis=1).shape[2]


65

In [30]:

out = network1.predict(X_train)
out


[[0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 

In [31]:
y_train

0  1  2  3  4  5  6  7
69   0  0  0  0  0  0  1  0
190  0  0  0  0  1  0  0  0
73   0  0  0  0  0  1  0  0
162  0  0  0  0  0  1  0  0
186  0  1  0  0  0  0  0  0
..  .. .. .. .. .. .. .. ..
83   0  0  0  0  0  1  0  0
39   0  0  0  0  0  1  0  0
140  0  1  0  0  0  0  0  0
70   0  0  0  0  0  0  1  0
131  0  0  0  0  0  1  0  0

[155 rows x 8 columns]

In [32]:
X_test.shape

(39, 65)

In [33]:
parameters = {
    'learning_rate': [0.5,0.8],
    'epochs': [1000,2000],
    'node_counts': [[3,3],[5,5],[10,10],[50,50],[100,100],[3,3,3],[5,5,5],[10,10,10],[20,20,20]],
    'activation_function': [(sigmoid,sigmoid_derivative),(relu,relu_derivative),(tanh,tanh_derivative)],

}
gs = GridSearcher(network1, parameters, pd.DataFrame(X_train), pd.DataFrame(y_train))
gs_results = gs.search()
gs_results

1 / 432: 0.05350787053952015
2 / 432: 0.07146696335273921
3 / 432: 0.02905353661932609
4 / 432: 0.1104498494800219
5 / 432: 0.022913302913302912
6 / 432: 0.027573260073260074
7 / 432: 0.06506950350990598
8 / 432: 0.012266312316715542
9 / 432: 0.06946932090301916
10 / 432: 0.011138411138411138
11 / 432: 0.010567067736185385
12 / 432: 0.010567067736185385
13 / 432: 0.010567067736185385
14 / 432: 0.010567067736185385
15 / 432: 0.010567067736185385
16 / 432: 0.0638040176198071
17 / 432: 0.01753319597069597
18 / 432: 0.028703703703703703
19 / 432: 0.045963545226703116
20 / 432: 0.015995816430020286
21 / 432: 0.04246583756282032
22 / 432: 0.07001736838430386
23 / 432: 0.010567067736185385
24 / 432: 0.05673904400469865
25 / 432: 0.03820174652933273
26 / 432: 0.010567067736185385
27 / 432: 0.01731060606060606
28 / 432: 0.060972222222222226


KeyboardInterrupt: 

In [ ]:
gs_results["test_score"].iloc[0]

array([0.19618056, 0.07407407, 0.04807692, 0.08504539, 0.04464286])

In [ ]:
gs_results["score_mean"].unique()

array([0.08960396, 0.04499002, 0.01452273, 0.07522672, 0.03616415,
       0.02337381, 0.07130482, 0.01951762, 0.06039978, 0.01817755,
       0.00883929, 0.05613495, 0.01382239, 0.03662442, 0.05446491,
       0.0205635 , 0.03809287, 0.06789895, 0.06909277, 0.02720154,
       0.01692833, 0.05539217, 0.04597683, 0.0248027 , 0.0404798 ,
       0.02381525, 0.06039317, 0.05903014, 0.02457636, 0.0419113 ,
       0.04023377, 0.0871844 , 0.05557678, 0.09452476, 0.06286417,
       0.02191144, 0.04889153, 0.04195395, 0.06753563, 0.02103175,
       0.02769222, 0.07343637, 0.01470814, 0.06265678, 0.06210229,
       0.04687996, 0.06987879, 0.08929224, 0.03752392, 0.01888113,
       0.06345015, 0.02032585, 0.05464656, 0.06524574, 0.0045928 ,
       0.02568841, 0.06414377, 0.05427285, 0.05514984, 0.03612816,
       0.06969607, 0.08247475, 0.05216267, 0.08314587, 0.02644494,
       0.05235752, 0.07771837, 0.01518479, 0.09112311, 0.03127212,
       0.06451915, 0.0158428 , 0.03716054, 0.09322437, 0.     

In [ ]:
nn_sklearn = MLPClassifier()

In [ ]:
parameters_sk = {
    'learning_rate_init': [0.01, 0.1,0.5,0.8],
    "learning_rate": ["constant"],
    'max_iter': [10,100,1000,2000],
    'hidden_layer_sizes': [[3,3],[5,5],[10,10],[50,50],[100,100],[3,3,3],[5,5,5],[10,10,10],[20,20,20]],
    'activation': ["logistic", "relu", "tanh"],
}

In [ ]:
sk_nn = MLPClassifier()

gs_sk = GridSearcher(sk_nn, parameters_sk, X_train, y_train)

In [ ]:
gs_results_sk = gs_sk.search()

1 / 432: 0.014263411138411137
2 / 432: 0.1046290963342017
3 / 432: 0.06972707586618877
4 / 432: 0.05651296072348703
5 / 432: 0.07472637055497763
6 / 432: 0.043243959325870426
7 / 432: 0.0
8 / 432: 0.019355292792792793
9 / 432: 0.01666666666666667
10 / 432: 0.0
11 / 432: 0.1272774739880003
12 / 432: 0.19470598845598847
13 / 432: 0.0
14 / 432: 0.2964404270480122
15 / 432: 0.32865897990897985
16 / 432: 0.04648779311608259
17 / 432: 0.06931174350388747
18 / 432: 0.05584842010934965
19 / 432: 0.023379240484503645
20 / 432: 0.04521747076023393
21 / 432: 0.12969391784619488
22 / 432: 0.009210526315789473
23 / 432: 0.01902126099706745
24 / 432: 0.009210526315789473
25 / 432: 0.0
26 / 432: 0.02777777777777778
27 / 432: 0.0
28 / 432: 0.0
29 / 432: 0.026785714285714284
30 / 432: 0.01111111111111111
31 / 432: 0.0
32 / 432: 0.16230583426235595
33 / 432: 0.14120549771865565
34 / 432: 0.0
35 / 432: 0.3774545169176008
36 / 432: 0.2948984933195459
37 / 432: 0.3019852661957925
38 / 432: 0.38416947818263